version: '3.9'
services:

  web:
    build: .
    ports:
      - "8000:8000"
    command: python ./BookShy/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: kartoza/postgis:15-3.3

    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - RUN_AS_ROOT=true
    ports:
      - '5432:5432'
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d gis"