# Generated by Django 3.2.7 on 2021-10-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0011_event_groupchat_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recently_viewed_novels',
            field=models.ManyToManyField(blank=True, related_name='recently_viewed_novels', to='novel.Novel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_novels',
            field=models.ManyToManyField(blank=True, related_name='saved_novel', to='novel.Novel'),
        ),
    ]
