# Generated by Django 3.2.7 on 2021-11-04 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0015_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default=uuid.uuid1, max_length=100, unique=True),
        ),
    ]
