# Generated by Django 3.2.7 on 2021-11-10 18:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0017_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=49),
        ),
        migrations.AddField(
            model_name='user',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], max_length=3),
        ),
    ]
