# Generated by Django 3.2.7 on 2021-11-21 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0020_auto_20211121_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='state',
            field=models.CharField(choices=[('u', 'unread'), ('r', 'read')], default='u', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='recently_viewed_chapters',
            field=models.ManyToManyField(blank=True, related_name='recently_viewed_chapters', to='novel.Chapters'),
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('u', 'unread'), ('r', 'read')], default='u', max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
