# Generated by Django 3.2.7 on 2021-11-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0022_remove_novel_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recently_viewed_audios',
        ),
        migrations.AddField(
            model_name='user',
            name='recently_viewed_audios',
            field=models.ManyToManyField(blank=True, null=True, related_name='recently_viewed_audios', to='novel.Audio'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_audios',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_audios',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_audios', to='novel.Audio'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_poems',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_poems',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_poems', to='novel.Poems'),
        ),
    ]
