# Generated by Django 3.2.7 on 2021-11-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0024_auto_20211123_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagram',
            new_name='country',
        ),
        migrations.AddField(
            model_name='novel',
            name='readers_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
