# Generated by Django 3.2.7 on 2021-11-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0025_auto_20211127_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='novel.profile'),
        ),
    ]
