# Generated by Django 3.2.7 on 2021-11-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0026_alter_novel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='bookFile',
        ),
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.ManyToManyField(to='novel.Genre'),
        ),
    ]
