# Generated by Django 3.2.7 on 2021-12-30 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0027_auto_20211128_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_field',
        ),
        migrations.RemoveField(
            model_name='user',
            name='my_field2',
        ),
        migrations.CreateModel(
            name='UserIntrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Traveling'), (2, 'Reading'), (3, 'Singing'), (4, 'Dancing'), (5, 'Movies')], max_length=9)),
                ('genre', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Action'), (2, 'Adventure'), (3, 'Comedy'), (4, 'Romance'), (5, 'Fantasy')], max_length=3)),
                ('language', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Spanish'), (2, 'English'), (3, 'Yoruba')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.fields.CharField, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
