# Generated by Django 3.2.7 on 2022-01-12 14:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0028_auto_20211230_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintrest',
            name='profile',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Author'), (2, 'Reader')], max_length=3),
        ),
        migrations.AddField(
            model_name='userintrest',
            name='timeline',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Medieval'), (2, 'Cyberpunk'), (3, 'Iceage'), (4, 'Ile-ife dynasty'), (5, 'Neolitic'), (6, 'Northern Caliphate'), (7, 'Paleolithic')], max_length=3),
        ),
    ]
