# Generated by Django 3.2.7 on 2022-01-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0029_auto_20220112_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poems',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
