# Generated by Django 3.2.7 on 2022-02-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0030_auto_20220113_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='novel',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poems',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
