# Generated by Django 3.2.7 on 2022-03-18 18:35

import django.core.validators
from django.db import migrations, models
import novel.models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0031_auto_20220201_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='bookFile',
            field=models.FileField(blank=True, upload_to='book_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), novel.models.valid_pdf_mimetype, novel.models.valid_size]),
        ),
        migrations.AlterField(
            model_name='audio',
            name='bookImage',
            field=models.ImageField(blank=True, null=True, upload_to='book/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg']), novel.models.valid_image_mimetype, novel.models.valid_size]),
        ),
        migrations.AlterField(
            model_name='poems',
            name='bookFile',
            field=models.FileField(blank=True, upload_to='book_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), novel.models.valid_pdf_mimetype, novel.models.valid_size]),
        ),
        migrations.AlterField(
            model_name='poems',
            name='bookImage',
            field=models.ImageField(blank=True, null=True, upload_to='book/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg']), novel.models.valid_image_mimetype, novel.models.valid_size]),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='state',
            field=models.CharField(choices=[('u', 'unread'), ('r', 'read'), ('f', 'finished')], default='u', max_length=1),
        ),
    ]
