# Generated by Django 3.2.7 on 2022-03-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0032_auto_20220318_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly',
            name='novels_of_week',
        ),
        migrations.AddField(
            model_name='weekly',
            name='novels_of_week',
            field=models.ManyToManyField(blank=True, related_name='weeknovel', to='novel.Novel'),
        ),
    ]
