# Generated by Django 3.2.7 on 2022-03-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0033_auto_20220319_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly',
            name='audios_of_week',
        ),
        migrations.AddField(
            model_name='weekly',
            name='audios_of_week',
            field=models.ManyToManyField(blank=True, null=True, related_name='weekaudios', to='novel.Audio'),
        ),
        migrations.RemoveField(
            model_name='weekly',
            name='authors_of_week',
        ),
        migrations.AddField(
            model_name='weekly',
            name='authors_of_week',
            field=models.ManyToManyField(blank=True, related_name='weekauthors', to='novel.Profile'),
        ),
        migrations.RemoveField(
            model_name='weekly',
            name='poems_of_week',
        ),
        migrations.AddField(
            model_name='weekly',
            name='poems_of_week',
            field=models.ManyToManyField(blank=True, related_name='weekpoems', to='novel.Poems'),
        ),
        migrations.RemoveField(
            model_name='weekly',
            name='special_feature',
        ),
        migrations.AddField(
            model_name='weekly',
            name='special_feature',
            field=models.ManyToManyField(blank=True, related_name='weekspecial', to='novel.Novel'),
        ),
    ]
