# Generated by Django 3.2.7 on 2022-05-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0036_alter_weekly_audios_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekly',
            old_name='audios_of_week',
            new_name='weekly_featured_audios',
        ),
        migrations.RenameField(
            model_name='weekly',
            old_name='novels_of_week',
            new_name='weekly_featured_novels',
        ),
        migrations.RenameField(
            model_name='weekly',
            old_name='poems_of_week',
            new_name='weekly_featured_poems',
        ),
    ]
