# Generated by Django 3.2.7 on 2022-12-16 11:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0037_auto_20220511_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userintrest',
            old_name='timeline',
            new_name='history',
        ),
        migrations.AddField(
            model_name='userintrest',
            name='faith',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Christain'), (2, 'Muslim'), (3, 'Judaism'), (4, 'Ile-ife dynasty'), (5, 'Neolitic'), (6, 'Northern Caliphate'), (7, 'Paleolithic')], max_length=3),
        ),
        migrations.AddField(
            model_name='userintrest',
            name='identity',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Women'), (2, 'Men'), (3, 'GenZ'), (4, 'Ile-ife dynasty'), (5, 'Neolitic'), (6, 'Northern Caliphate'), (7, 'Paleolithic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userintrest',
            name='profile',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Author'), (2, 'Reader')], max_length=3),
        ),
    ]
