# Generated by Django 3.2 on 2021-08-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_rename_numnber_chapters_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='saved_novels',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_novels',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_novel', to='novel.Novel'),
        ),
    ]
